version: "3"
services:
  app:
    image: node:16
    volumes:
      - .:/workspace:delegated
      - node_modules:/workspace/node_modules
    command: tail -f /dev/null
    working_dir: /workspace
volumes: 
  node_modules: